apiVersion: v1
kind: Namespace
metadata:
  name: tshoot-1
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: tshoot-1
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    run: another-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: tshoot-1
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: nginx-latest
        image: ngix:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "200Mi"
          requests:
            cpu: "0.25"
            memory: "100Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tshoot-2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: tshoot-2
spec:
  containers:
  - image: redis:6.2
    name: redis
    resources:
      requests:
        cpu: "4"
        memory: "500Mi"
      limits:
        cpu: "4"
        memory: "750Mi"
  restartPolicy: Always
